[arraybuilder]
display_name = "Array Builder"
id = "arraybuilder"
type = "all"
input_device = "any"
flow_target = "data"
description = "Custom const string arrays for use with array-item sub-nodes.\nDefine arrays in the Functions Code section, reference them by name in array-items."
state_display = ""
combo = "// Define your arrays here. Example:\n// const string Teams[] = { \"Attackers\", \"Defenders\" };\n// define TEAMS_COUNT = 2;"
