import type { FlowProject, FlowGraph, FlowVariable, FlowProfile, ProfileSwitchConfig } from '$lib/types/flow';
import {
	generateFlowGpc,
	collectPersistVars,
	flowVarsToPersistVars,
	generateBitpackPersistence,
	type PersistVar,
} from './codegen';
import { generateGameplayGpc, generateGameplayGpcStandalone } from './codegen-gameplay';

/**
 * Generate a single merged GPC script from an entire FlowProject.
 *
 * Combines the menu flow (state machine) and gameplay flow (parallel modules)
 * into one cohesive script. Shared variables are declared once and used by both.
 *
 * Persistence is coordinated across both flows:
 *   - SPVAR_1 = data-exists marker
 *   - SPVAR_2-5 = reserved for user manual use
 *   - SPVAR_6+ = auto-generated bitpacked data
 */
export interface MergedFlowResult {
	code: string;
	extraFiles: Record<string, string>;
}

export function generateMergedFlowGpc(project: FlowProject): MergedFlowResult {
	const menuFlow = project.flows.find((f) => f.flowType === 'menu');
	const gameplayFlow = project.flows.find((f) => f.flowType === 'gameplay');

	const hasMenu = menuFlow && menuFlow.nodes.length > 0;
	const hasGameplay = gameplayFlow && gameplayFlow.nodes.some((n) => n.type === 'module' || n.type === 'custom');

	const profiles = project.profiles ?? [];
	const profileCount = profiles.length;

	// If only one flow has content, just generate that one
	if (hasMenu && !hasGameplay) {
		return { code: generateFlowGpc(menuFlow, profileCount), extraFiles: {} };
	}
	if (!hasMenu && hasGameplay) {
		const gameplayResult = generateGameplayGpc(gameplayFlow!);
		return {
			code: generateGameplayGpcStandalone(gameplayFlow!),
			extraFiles: gameplayResult.extraFiles,
		};
	}
	if (!hasMenu && !hasGameplay) {
		return { code: '// Empty flow project — add nodes to generate code\n', extraFiles: {} };
	}

	// Both flows have content — merge them
	// Skip persistence in menu codegen — we generate combined persistence below
	const gameplayResult = generateGameplayGpc(gameplayFlow!);
	const menuCode = generateFlowGpc(menuFlow!, profileCount, { skipPersistence: true });

	// Collect combined persist vars from all sources
	const combinedPersistVars = collectCombinedPersistVars(project, menuFlow!, gameplayFlow!, profileCount);

	const lines: string[] = [];

	lines.push(`// ====================================================`);
	lines.push(`// This script was generated by ZenForge.`);
	lines.push(`// If you want to make scripts easily maintainable:`);
	lines.push(`// consider downloading the ZenForge for free at`);
	lines.push(`// https://github.com/masshirodev/zenforge`);
	lines.push(`// ====================================================`);
	lines.push(`// Project version: ${project.version}`);
	lines.push(`// Generated at: ${new Date(project.updatedAt).toLocaleString()}`);

	if (profileCount > 1) {
		lines.push(`// Profiles: ${profiles.map((p) => p.name).join(', ')}`);
	}

	lines.push(`// ====================================================`);
	lines.push('');

	// Parse menu code to separate const declarations from functions
	// GPC requires const declarations before any function definitions
	const menuLines = menuCode.split('\n');
	const mainStartIdx = menuLines.findIndex((l) => l.trim().startsWith('main {'));
	const initStartIdx = menuLines.findIndex((l) => l.trim().startsWith('init {'));

	const sharedVarNames = new Set(project.sharedVariables.map((v) => v.name));

	// Everything before init is declarations/functions
	// Strip imports (already at top) and shared variable re-declarations
	const preInit = menuLines
		.slice(0, initStartIdx >= 0 ? initStartIdx : mainStartIdx >= 0 ? mainStartIdx : menuLines.length)
		.filter((l) => {
			const trimmed = l.trim();
			if (trimmed.startsWith('import ')) return false;
			if (sharedVarNames.size > 0) {
				const varMatch = trimmed.match(/^(?:int|int8|int16|int32)\s+(\w+)/);
				if (varMatch && sharedVarNames.has(varMatch[1])) return false;
			}
			return true;
		});

	// Split preInit into const declarations (string/image) and the rest (vars/functions)
	// Const declarations must appear before imports (which contain function defs)
	const constLines: string[] = [];
	const nonConstLines: string[] = [];
	let inConstBlock = false;
	for (const line of preInit) {
		const trimmed = line.trim();
		if (trimmed.startsWith('const string ') || trimmed.startsWith('const image ') || trimmed.startsWith('// ===== STRING TABLES') || trimmed.startsWith('// ===== IMAGE DATA')) {
			inConstBlock = true;
		}
		if (inConstBlock) {
			constLines.push(line);
			// End of a const block: closing brace of multi-line const or single-line const
			if (trimmed.startsWith('};') || (trimmed.startsWith('const ') && trimmed.endsWith(';'))) {
				inConstBlock = false;
			}
			// Empty line after const block
			if (trimmed === '' && constLines.length > 0) {
				inConstBlock = false;
			}
		} else {
			nonConstLines.push(line);
		}
	}

	// Profile variables (when multiple profiles are configured)
	if (profileCount > 1) {
		lines.push(`// ===== PROFILE SYSTEM =====`);
		lines.push(`define FLOW_PROFILE_COUNT = ${profileCount};`);
		lines.push(`int Flow_CurrentProfile = 0;`);
		lines.push('');
	}

	// Shared variables
	if (project.sharedVariables.length > 0) {
		lines.push(`// ===== SHARED VARIABLES =====`);
		for (const v of project.sharedVariables) {
			lines.push(generateVarDecl(v, profileCount));
		}
		lines.push('');
	}

	// Shared code
	if (project.sharedCode.trim()) {
		lines.push(`// ===== SHARED CODE =====`);
		lines.push(project.sharedCode.trim());
		lines.push('');
	}

	// Gameplay variables (exclude any already declared as shared)
	const gameplayVars = gameplayResult.variables.filter((decl) => {
		const match = decl.match(/(?:int|int8|int16|int32)\s+(\w+)/);
		return match ? !sharedVarNames.has(match[1]) : true;
	});

	// Gameplay defines (button params, weapon counts, etc.)
	if (gameplayResult.defines.length > 0) {
		lines.push(`// ===== GAMEPLAY DEFINES =====`);
		lines.push(...gameplayResult.defines);
		lines.push('');
	}

	if (gameplayVars.length > 0) {
		lines.push(`// ===== GAMEPLAY VARIABLES =====`);
		lines.push(...gameplayVars);
		lines.push('');
	}

	// Emit const declarations (string tables, image data) before imports
	if (constLines.length > 0) {
		lines.push(...constLines);
		if (constLines[constLines.length - 1]?.trim() !== '') lines.push('');
	}

	// Imports for common helpers (after const declarations, since they contain functions)
	lines.push(`import common/helper;`);
	lines.push(`import common/oled;`);
	if (combinedPersistVars.length > 0) {
		lines.push(`import common/bitpack;`);
	}
	lines.push('');

	// Menu flow declarations and functions (non-const parts)
	lines.push(`// ===== MENU FLOW =====`);
	lines.push(...nonConstLines);

	// Gameplay combos
	if (gameplayResult.combos.length > 0) {
		lines.push(`// ===== GAMEPLAY COMBOS =====`);
		lines.push(...gameplayResult.combos);
	}

	// Gameplay functions
	if (gameplayResult.functions.length > 0) {
		lines.push(`// ===== GAMEPLAY FUNCTIONS =====`);
		lines.push(...gameplayResult.functions);
		lines.push('');
	}

	// Combined persistence (bitpack-based, covers both flows)
	if (combinedPersistVars.length > 0) {
		lines.push(`// ===== PERSISTENCE =====`);
		lines.push(generateBitpackPersistence(combinedPersistVars));
		lines.push('');
	}

	// Merged init block
	const hasGameplayInit = gameplayResult.initCode.length > 0;
	const needsInit = initStartIdx >= 0 || hasGameplayInit || combinedPersistVars.length > 0;

	if (needsInit) {
		lines.push(`// ===== INIT =====`);
		lines.push(`init {`);

		if (initStartIdx >= 0) {
			const initEndIdx = findBlockEnd(menuLines, initStartIdx);
			const menuInitBody = menuLines.slice(initStartIdx + 1, initEndIdx);
			if (hasGameplayInit) {
				lines.push(`    // --- Menu Init ---`);
			}
			lines.push(...menuInitBody);
		}

		if (hasGameplayInit) {
			if (initStartIdx >= 0) lines.push('');
			lines.push(`    // --- Gameplay Init ---`);
			lines.push(...gameplayResult.initCode);
		}

		if (combinedPersistVars.length > 0) {
			lines.push(`    Flow_Load();`);
		}

		lines.push(`}`);
		lines.push('');
	}

	// Merged main block
	lines.push(`// ===== MAIN LOOP =====`);
	lines.push(`main {`);

	// Profile switching (before menu/gameplay code)
	if (profileCount > 1 && project.profileSwitch) {
		lines.push('');
		lines.push(`    // --- Profile Switching ---`);
		lines.push(...generateProfileSwitchCode(project.profileSwitch, profileCount));
	}

	// Menu state dispatch (extract main body)
	if (mainStartIdx >= 0) {
		const mainEndIdx = findBlockEnd(menuLines, mainStartIdx);
		const menuMainBody = menuLines.slice(mainStartIdx + 1, mainEndIdx);
		lines.push(`    // --- Menu Flow ---`);
		lines.push(...menuMainBody);
	}

	// Gameplay triggers
	if (gameplayResult.mainLoopCode.length > 0) {
		lines.push('');
		lines.push(`    // --- Gameplay Flow ---`);
		lines.push(...gameplayResult.mainLoopCode);
	}

	lines.push(`}`);

	return { code: lines.join('\n'), extraFiles: gameplayResult.extraFiles };
}

// ==================== Persistence Collection ====================

/**
 * Collect all persist variables from a merged project, deduplicating by name.
 * Includes shared vars, menu flow vars, gameplay flow vars, and special
 * array persistence for Weapons_RecoilValues when applicable.
 */
function collectCombinedPersistVars(
	project: FlowProject,
	menuFlow: FlowGraph,
	gameplayFlow: FlowGraph,
	profileCount: number
): PersistVar[] {
	const result: PersistVar[] = [];
	const seen = new Set<string>();

	function addVars(vars: FlowVariable[]) {
		const pvars = flowVarsToPersistVars(vars, profileCount);
		for (const pv of pvars) {
			if (!seen.has(pv.name)) {
				result.push(pv);
				seen.add(pv.name);
			}
		}
	}

	// Shared variables
	const sharedPersist = project.sharedVariables.filter((v) => v.persist);
	addVars(sharedPersist);

	// Menu flow persist vars
	if (menuFlow.settings.persistenceEnabled) {
		addVars(collectPersistVars(menuFlow));
	}

	// Gameplay flow persist vars (module options with persist: true)
	addVars(collectPersistVars(gameplayFlow));

	// Special: Weapons_RecoilValues array persistence
	// When weapondata module exists and a recoil module uses it (not timeline which is hardcoded)
	const hasWeapondata = gameplayFlow.nodes.some((n) => n.moduleData?.moduleId === 'weapondata');
	const hasRecoilModule = gameplayFlow.nodes.some(
		(n) =>
			n.moduleData?.needsWeapondata &&
			n.moduleData.moduleId !== 'weapondata' &&
			n.moduleData.moduleId !== 'antirecoil_timeline'
	);

	if (hasWeapondata && hasRecoilModule && !seen.has('Weapons_RecoilValues')) {
		result.push({
			name: 'Weapons_RecoilValues',
			min: -100,
			max: 100,
			defaultValue: 0,
			arrayLoop: {
				countExpr: 'WEAPON_COUNT * 2',
				indexVar: '_bp_loop_i',
			},
		});
		seen.add('Weapons_RecoilValues');
	}

	return result;
}

// ==================== Helpers ====================

function generateVarDecl(v: FlowVariable, profileCount: number = 0): string {
	if (v.perProfile && profileCount > 1 && v.type !== 'string') {
		const defaults = Array(profileCount).fill(v.defaultValue).join(', ');
		return `${v.type} ${v.name}[${profileCount}] = { ${defaults} };`;
	}
	if (v.type === 'string') {
		const size = v.arraySize ?? 32;
		return `int8 ${v.name}[${size}];`;
	}
	return `${v.type} ${v.name} = ${v.defaultValue};`;
}

/**
 * Generate profile switch code for the main loop.
 */
function generateProfileSwitchCode(config: ProfileSwitchConfig, profileCount: number): string[] {
	const lines: string[] = [];
	const mod = config.modifier ? `get_val(${config.modifier}) && ` : '';

	lines.push(`    if(${mod}event_press(${config.next})) {`);
	lines.push(`        Flow_CurrentProfile = Flow_CurrentProfile + 1;`);
	lines.push(`        if(Flow_CurrentProfile >= ${profileCount}) Flow_CurrentProfile = 0;`);
	lines.push(`    }`);

	if (config.prev) {
		lines.push(`    if(${mod}event_press(${config.prev})) {`);
		lines.push(`        if(Flow_CurrentProfile > 0) Flow_CurrentProfile = Flow_CurrentProfile - 1;`);
		lines.push(`        else Flow_CurrentProfile = ${profileCount - 1};`);
		lines.push(`    }`);
	}

	return lines;
}

/**
 * Find the closing brace index for a block starting at `startIdx`.
 */
function findBlockEnd(lines: string[], startIdx: number): number {
	let depth = 0;
	for (let i = startIdx; i < lines.length; i++) {
		for (const ch of lines[i]) {
			if (ch === '{') depth++;
			if (ch === '}') depth--;
			if (depth === 0 && i > startIdx) return i;
		}
	}
	return lines.length - 1;
}
